code refactoring
YC/another_authenticator pull request #16
Opened 2024-09-28 08:36 UTC by bhargavraviya

Flutter Upgrade from scratch

- change code syntax and refactoring according new flutter version 

please check it and merge @YC

2024-09-28 10:15 UTC, YC requested changes

2024-09-28 10:15 UTC, YC commented on lib/config/routes.dart
> +  static const String main = '';
The usage of `AppRoutes.main` in subsequent variables is a bit strange. 
Can you please change it to e.g. `static const String add = '/add';`

2024-09-28 10:15 UTC, YC commented on lib/pages/add.dart
> -      // TODO: Fix exception handling
This comment is still unresolved. 
Please add it back.

2024-09-28 10:15 UTC, YC commented on lib/pages/android/list_item.dart
> +  static const double progressIndicatorDimension = 25;
The variable should still be private

2024-09-28 10:15 UTC, YC commented on lib/pages/cupertino/home.dart
> -                // TODO: Transition to new type
This TODO is not resolved. 
Please add it back.

2024-09-28 10:15 UTC, YC commented on lib/pages/cupertino/list_item.dart
> +  static const double progressIndicatorDimension = 25;
The variable should still be private

2024-09-28 10:15 UTC, YC commented on lib/pages/settings.dart
> +import '../l10n/constants.dart' as constants;
Should probably turn this into a class and show Constants instead.

2024-09-28 10:15 UTC, YC commented on lib/pages/android/home.dart
> -                  // TODO: Transition to new type
This is not yet resolved. 
Please add comment back.

2024-10-01 04:28 UTC, bhargavraviya commented on lib/config/routes.dart
> +  static const String main = '';
remove static const String main = ''; line please check it

2024-10-01 09:55 UTC, YC approved these changes

2024-10-01 09:55 UTC, merged

2024-10-01 09:55 UTC, YC commented
Thanks!